### ISSUE TITLE
Bug: Cannot decode response body

### ISSUE THREAD

**Issue by derdualist** [IBM/gauge-api-steps#55]
```
'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
Traceback (most recent call last):
  File "/Users/daniel.kuehn/Library/Python/3.12/lib/python/site-packages/getgauge/executor.py", line 33, in execute_method
    step.impl(*params)
  File "/Users/daniel.kuehn/Library/Python/3.12/lib/python/site-packages/gauge_api_steps/api_steps.py", line 178, in make_request
    report_response_info(resp, resp_body)
  File "/Users/daniel.kuehn/Library/Python/3.12/lib/python/site-packages/gauge_api_steps/reporting.py", line 41, in report_response_info
    print_and_report(f"< {resp_body.decode()}")
                          ^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

Happens when config props for logging response is turned on.

**Comment by derdualist** [comment]
Closed with #56
